---
- name: Installs ansible jenkins plugin 
  hosts: all 
  gather_facts: no
  tasks:

  - name: Install Ansible plugin 
    jenkins_plugin:
      name: Ansible 
      url_username: "{{ jenkins_username }}"
      url_password: "{{ jenkins_password }}"
      url: "{{ jenkins_url }}" 
