---
- name: Installs ansible jenkins plugin 
  hosts: "{{ hosts }}"
  gather_facts: yes
  become: true
  tasks:

  - name: Install Ansible plugin 
    jenkins_plugin:
      name: Ansible 
      params: "{{ jenkins_username }}"
      url_password: "{{ jenkins_password }}"
      url: "{{ jenkins_url }}" 
    register: plugin_install

#  - name: Enable plugin
#    jenkins_plugin:
#      name: Ansible
#      state: enabled

  - name: Restart Jenkins
    service:
      name: jenkins
      state: restarted
    when: plugin_install.changed
