---
- name: Installs ansible jenkins plugin 
  hosts: "{{ hosts }}"
  gather_facts: yes
  become: true
  tasks:

  - name: Install Ansible plugin 
    jenkins_plugin:
      name: Ansible Tower 
      url_username: "{{ jenkins_username }}"
      url_password: "{{ jenkins_password }}"
      url: "{{ jenkins_url }}"
      state: pinned 
    register: plugin_install

  - name: Restart Jenkins
    service:
      name: jenkins
      state: restarted
    when: plugin_install.changed

  - name: Making Sure Jenkins restarts
    service: 
      name: jenkins
      state: restarted
